# This is a basic workflow to help you get started with Actions

name: Veracode Sandbox Upload & Scan with AutoPackage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
        with: 
          java-version: '8'

      - name: Package App
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output ./veracode-artifacts --trust --debug

      - name: List files in the repository
        run: |
          ls -al ${{ github.workspace }}

      - uses: veracode/veracode-uploadandscan-action@0.2.7 # Run the uploadandscan action. Inputs are described above.
        with:
          appname: '${{ secrets.VERACODE_APP_NAME }}'
          filepath: app/target/verademo.war
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          sandboxname: Github-Autopackages
          createsandbox: true
          createprofile: false
